# Generated by Django 5.1.6 on 2025-02-25 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(blank=True, null=True, verbose_name='Wiki url')),
                ('question', models.TextField(blank=True, null=True, verbose_name='User question')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Article text')),
                ('result_summary', models.TextField(blank=True, null=True, verbose_name='Result Summary')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='AI Confidence Score')),
                ('sources', models.JSONField(blank=True, null=True, verbose_name='Alternative sources')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
