# Generated by Django 5.1.6 on 2025-03-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0003_wikipediaarticle_wikipediaarticlejson_customuser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="crosschecker_db",
        ),
    ]
