"""
Django settings for crosschecker project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure log directory exists
log_dir = os.path.join(BASE_DIR, 'info_log')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-qgxpcf$&mo797_pz)c67%%d269bqcr)*4yd6k+yg*_r3mo3+3w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'  # Default to False for production

# Allowed hosts for production (update with your domain or cloud IP)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'checker',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middlewares
    "checker.middlewares.LogRequestResponseMiddlewares.ErrorHandlingMiddleWare",
    "checker.middlewares.LogRequestResponseMiddlewares.DebugLoggingMiddleware",
    "checker.middlewares.LogRequestResponseMiddlewares.InfoLoggingMiddleware",
    "checker.middlewares.LogRequestResponseMiddlewares.WarningLoggingMiddleware",
    "checker.middlewares.LogRequestResponseMiddlewares.CriticalLoggingMiddleware",
    "checker.middlewares.TimeMiddleWare.PerformanceMiddleware",
]

ROOT_URLCONF = 'crosschecker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crosschecker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE'),
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # For production

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'checker.CustomUser'

# Security settings for production
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'  # Redirect HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # Enforce HTTPS for 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
CSRF_COOKIE_SECURE = False  # Use secure cookies for CSRF
SESSION_COOKIE_SECURE = False  # Use secure cookies for sessions

# Logging configuration
LOGGING = {
    "version": 1,
    'disable_existing_loggers': False,
    "formatters": {
        "verbose": {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        "simple": {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',  # Only INFO and above in production
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'info.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'file_app': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'info_app.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'debug_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'debug.log'),
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'info_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'info.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'warning_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'warning.log'),
            'formatter': 'verbose',
            'level': 'WARNING',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'error.log'),
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        'critical_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'info_log', 'critical.log'),
            'formatter': 'verbose',
            'level': 'CRITICAL',
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "checker": {
            "handlers": ["console", "file_app"],
            "level": "INFO",
            "propagate": True,
        },
        'debug': {
            'handlers': ['debug_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'info': {
            'handlers': ['info_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'warning': {
            'handlers': ['warning_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'error': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'critical': {
            'handlers': ['critical_file'],
            'level': 'CRITICAL',
            'propagate': False,
        },
    }
}